# Generated by Django 4.2 on 2024-11-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.IntegerField(default=0, verbose_name='Mejor Puntaje')),
                ('last_score', models.IntegerField(default=0, verbose_name='Último Puntaje')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_data', to='cleanitup.player', verbose_name='Jugador')),
            ],
        ),
    ]
